<!DOCTYPE html>
<html lang="en">
<head>
    <title>Redirect - TOPIAM</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="robots" content="noindex, nofollow, nocache, noarchive"/>
    <meta
            name="viewport"
            content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no"
    />
</head>
<style>
</style>
<body>
<noscript>
    <p>
        <strong>Note:</strong> Since your browser does not support JavaScript, you must press the
        Continue button once to proceed.
    </p>
</noscript>
<div id="root">
</div>
<script type="text/javascript" nonce="${nonce}">
    window.opener.postMessage('${result}', '*')
    window.close()
</script>
</body>
</html>
